"""initialize tables

Revision ID: 1d2945e93243
Revises: 6c790a24b882
Create Date: 2023-08-28 12:45:04.007624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2945e93243'
down_revision = '6c790a24b882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_user_items_buyer_id_users')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_user_items_item_id_items')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bids')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_items_listed_by_users'), 'users', ['listed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_listed_by_users'), type_='foreignkey')
        batch_op.drop_column('listed_by')

    op.create_table('bids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.Column('seller_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='fk_bids_buyer_id_users'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_bids_item_id_items'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='fk_bids_seller_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_items')
    # ### end Alembic commands ###
